# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:

env_files:
  github_token: /root/projects/keys/main

builds:
  -
    binary: ctrl
    id: ctrl
    ldflags: -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
      - openbsd
      - netbsd
    goarch:
      - amd64
      - arm64
      - ppc64
      - mips64
    goarm:
      - 7

release:
  draft: false

archives:
  -
    id: "ctrl"
    builds: ['ctrl']
    format: tar.gz
    name_template: "{{.ProjectName}}-{{.Version}}-{{.Os}}-{{.Arch}}"
    files:
      - LICENSE
      - NOTICE

nfpms:
  -
    id: "ctrl"
    builds: ['ctrl']
    formats:
      - deb
      - rpm
    vendor: "Eltaline <eltaline.ou@gmail.com>"
    homepage: "https://elta.ee/"
    maintainer: "Andrey Kuvshinov <syslinux@protonmail.com>"
    description: "Remote cTRL API Server"
    license: "Apache 2.0"
    file_name_template: "{{.ProjectName}}-{{.Version}}-{{.Os}}-{{.Arch}}"

    bindir: /usr/sbin

    dependencies:
      - systemd
      - logrotate

    empty_folders:
      - /etc/ctrl
      - /var/log/ctrl
      - /var/lib/ctrl
      - /usr/share/ctrl

    contents:
      - src: "conf/systemd/ctrl.service"
        dst: "/lib/systemd/system/ctrl.service"

      - src: "conf/logrotate.d/ctrl"
        dst: "/etc/logrotate.d/ctrl"

      - src: "LICENSE"
        dst: "/usr/share/ctrl/LICENSE"

      - src: "NOTICE"
        dst: "/usr/share/ctrl/NOTICE"

      - src: "conf/ctrl/ctrl.conf"
        dst: "/etc/ctrl/ctrl.conf"
        type: config

      - src: "conf/ctrl/ips-localhost.conf"
        dst: "/etc/ctrl/ips-localhost.conf"
        type: config

      - src: "conf/ctrl/uss-localhost.conf"
        dst: "/etc/ctrl/uss-localhost.conf"
        type: config

    scripts:
      postinstall: "scripts/postinstall.sh"

scoop:

  commit_author:
    name: "Andrey Kuvshinov"
    email: syslinux@protonmail.com
  homepage: "https://elta.ee/"
  license: Apache 2.0

brews:
 -
   commit_author:
     name: "Andrey Kuvshinov"
     email: syslinux@protonmail.com
   homepage: "https://elta.ee/"
   goarm: 7

snapshot:
  name_template: "{{.Version}}-master"
changelog:
  sort: asc
  filters:
    exclude:
    - README
    - OPTIONS
    - Readme
    - Options
    - Image
    - Script
    - Docker
    - Typo
    - "via upload"
    - goreleaser
