# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:

env_files:
  github_token: /root/projects/keys/main

builds:
  -
    binary: ctrl
    id: ctrl
    ldflags: -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
      - openbsd
      - netbsd
#      - solaris
#      - darwin
    goarch:
      - amd64
      - arm64
      - ppc64
      - mips64
    goarm:
      - 7

release:
  draft: false

archives:
  -
    id: "ctrl"
    builds: ['ctrl']
    format: tar.gz
    name_template: "{{.ProjectName}}-{{.Version}}-{{.Os}}-{{.Arch}}"
    files:
      - LICENSE
      - NOTICE

nfpms:
  -
    id: "ctrl"
    builds: ['ctrl']
    formats:
      - deb
      - rpm
    vendor: "Eltaline"
    homepage: "https://wzd.dev/"
    maintainer: "Andrey Kuvshinov <dev@wzd.dev>"
    description: "Remote cTRL API Server"
    license: "Apache 2.0"
    name_template: "{{.ProjectName}}-{{.Version}}-{{.Os}}-{{.Arch}}"

    bindir: /usr/sbin

    dependencies:
      - systemd
      - logrotate

    empty_folders:
      - /etc/ctrl
      - /var/log/ctrl
      - /var/lib/ctrl
      - /usr/share/ctrl

    files:
      "conf/systemd/ctrl.service": "/lib/systemd/system/ctrl.service"
      "conf/logrotate.d/ctrl": "/etc/logrotate.d/ctrl"
      "LICENSE": "/usr/share/ctrl/LICENSE"
      "NOTICE": "/usr/share/ctrl/NOTICE"

    config_files:
      "conf/ctrl/ctrl.conf": "/etc/ctrl/ctrl.conf"
      "conf/ctrl/ips-localhost.conf": "/etc/ctrl/ips-localhost.conf"
      "conf/ctrl/uss-localhost.conf": "/etc/ctrl/uss-localhost.conf"

    scripts:
      postinstall: "scripts/postinstall.sh"

scoop:

  commit_author:
    name: "Andrey Kuvshinov"
    email: dev@wzd.dev
  homepage: "https://wzd.dev/"
  license: Apache 2.0

brews:
 -
   commit_author:
     name: "Andrey Kuvshinov"
     email: dev@wzd.dev
   homepage: "https://wzd.dev/"
   goarm: 7

snapshot:
  name_template: "{{.Version}}-master"
changelog:
  sort: asc
  filters:
    exclude:
    - README
    - OPTIONS
    - Readme
    - Options
    - Image
    - Script
    - Docker
    - Typo
    - "via upload"
    - goreleaser
