#!/bin/sh
### BEGIN INIT INFO
# Provides: ctrl
# Required-Start:       $syslog $local_fs $remote_fs $network
# Required-Stop:        $syslog $local_fs $remote_fs
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description: cTRL Service
### END INIT INFO

. /lib/lsb/init-functions
DAEMON=ctrl
USER="ctrl"
GROUP="ctrl"
DBDIR="/var/lib/ctrl"
LOGDIR="/var/log/ctrl"
RUNDIR="/run/ctrl"
PIDFILE=/run/ctrl/ctrl.pid
DESC="cTRL Service"
start() {

	if [ -z `getent group ctrl` ]; then
		groupadd ctrl
	fi

	if [ -z `getent passwd ctrl` ]; then
		useradd ctrl -g ctrl
	fi

	test -d $DBDIR || install --mode=755 --owner=ctrl --group=ctrl --directory $DBDIR
	test -d $LOGDIR || install --mode=755 --owner=ctrl --group=ctrl --directory $LOGDIR
	test -d $RUNDIR || install --mode=755 --owner=ctrl --group=ctrl --directory $RUNDIR

	log_daemon_msg "Starting $DESC\n"
	start-stop-daemon -q -b -u $USER -g $GROUP -p $PIDFILE --start --exec /usr/sbin/ctrl
	if [ $? -ne 0 ]; then
		log_failure_msg "Failed"
		exit 1
	fi
	if [ $? -eq 0 ]; then
		log_success_msg "cTRL Started"
	fi
	exit 0

}

stop() {

	log_daemon_msg "Stopping $DESC\n"
	start-stop-daemon -q -p $PIDFILE --stop
	if [ $? -ne 0 ]; then
		log_failure_msg "Failed"
		exit 1
	fi
	if [ $? -eq 0 ]; then
		log_success_msg "cTRL Stopped"
	fi

}

force_reload() {

	stop
	start

}

case "$1" in

	start)
		start
		;;
	stop)
		stop
		;;
	force-reload)
		force_reload
		;;
	restart)
		stop
		start
		;;

	*)
		echo "$Usage: $DAEMON {start|stop|force-reload|restart}"
		exit 2

esac
